export type Technology =
  | 'Python'
  | 'AWS'
  | 'Docker'
  | 'Terraform'
  | 'React'
  | 'NEXT.JS'
  | 'TypeScript'
  | 'JavaScript'
  | '.NET'
  | 'Markdown'
  | 'Go'
  | 'Auth0'
  | 'HTML'
  | 'CSS'
  | 'Tailwind'
  | 'Polars'
  | 'Pandas'
  | 'Databricks'
  | 'Quarto'
  | 'LaTeX'
  | 'Numerical Methods'
  | 'Linear Algebra'
  | 'Nonlinear Systems'
  | 'Error Analysis';
